services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - cache
  db:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: '0000'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  cache:
    image: 'redis:latest'
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-cache:/data
    
volumes:
  postgres:
  redis-cache: 