services:
  server:
    build: .
    ports:
      - "5000:3000"
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '0000'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      
volumes:
  postgres: